### ISSUE TITLE
Show more information from reverb server with --debug

### ISSUE THREAD

**Issue by tarreislam** [laravel/reverb#102]
It would be great if `--debug` also showed more details, for example when something besides 200 OK happends it would be great to have more details than "internal server error", it would also help when doing bug issues.

Kind regards

**Comment by jimmy-lilly** [comment]
Would like to see Pusher Channel broadcast(s) displayed when debug on.

**Comment by joedixon** [comment]
Thanks for the feedback, I will give this some thought some thought and see what would be involved to impletment.
