### ISSUE TITLE
Allow to configure Reverb base route

### ISSUE THREAD

**Issue by robsontenorio** [laravel/reverb#103]
Currently all Reverb routes are hardcoded with `/app`.

This make difficult to configure Nginx reverse proxy based on `location` directive when you are using the same server to host your App + Laravel Reverb. Mainly because some cloud providers does not allow to expose on Internet multiples ports.

The only alternative currently is to configure as `location /app/ { ... }` but it is not safe and can lead to unexpected results.

### Suggestion:

Add a new Reverb config  like this

```php
    'base_route' => env('REVERB_BASE_ROUTE', '/app')
```

**Comment by joedixon** [comment]
It's configured this way to allow use with Echo and the Pusher SDK so I don't think this is something we plan to change right now.
