### ISSUE TITLE
Pusher error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0"

### ISSUE THREAD

**Issue by iqbalhasandev** [laravel/reverb#104]
### Reverb Version

v1.0.0-beta4

### Laravel Version

v11.0.7

### PHP Version

8.2.16

### Description

I have Laravel reverb served in a subdomain on my server. Now I have connected to that subdomain from local with laravel-echo and there is no problem in eco connection.

But when I try to fire an event from the back-end I keep getting this error "Pusher error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0" ". But I can't understand why it is showing.
- The error message
   (https://flareapp.io/share/17DxbD97)

- my reveb connection .env
  ![image](https://github.com/laravel/reverb/assets/39612205/34621f17-4459-4753-9382-c63a6e38003d)
 
- server reverb console 
  ![image](https://github.com/laravel/reverb/assets/39612205/d30591d0-fd3d-4be4-9df3-7bcc95554297)

But when I am locally using an application as a socket only and firing events from another application then everything is working fine only when I deploy reverb on the server there is a problem.

- Local Reverb console
  ![image](https://github.com/laravel/reverb/assets/39612205/3c3ae987-ecfe-4f84-ad0b-ef09840424df)

My concept is that there will be a reverb server in a subdomain and everyone will connect to that reverb server subdomain from another domain.

**Comment by crynobone** [comment]
Seem like `socket.iqbalhasan.dev` is not running on PHP 8.2

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by iqbalhasandev** [comment]
but my server running php 8.2

**Comment by iqbalhasandev** [comment]
if serve

> Seem like `socket.iqbalhasan.dev` is not running on PHP 8.2. The posted error may come from Reverb but exception originated from Composer.

But my server is running php 8.2. server. Since PHP 8.2 is running, Laravel-Echo is connecting to the server. I have checked many times
