### ISSUE TITLE
Laravel reverb config tls variables

### ISSUE THREAD

**Issue by vatsake** [laravel/reverb#105]
In my dev I'm using a self signed certificate, so I have to put the cert path in .env.
In my production there's a nginx reverse proxy, so I don't need a certificate in my .env.

But the problem is if the options "tls" is NOT empty then the server will run in secure mode.

Servers/Reverb/Factory.php L54
```
$uri = empty($options['tls']) ? "{$host}:{$port}" : "tls://{$host}:{$port}";
```

My reverb.php config
```
'servers' => [
        'reverb' => [
           ...
            'options' => [
                'tls' => [ //tls is ALWAYS not empty
                    'local_cert' =>env('REVERB_CERT')
                ],
            ],
        ]
]
```

**Comment by joedixon** [comment]
Thanks, I'll get a fix up for this as soon as I can.

**Comment by joedixon** [comment]
This should be resolved in the next release: https://github.com/laravel/reverb/pull/85
