### ISSUE TITLE
SSL Error  with pusher and reverb

### ISSUE THREAD

**Issue by neoteknic** [laravel/reverb#109]
### Reverb Version

beta4

### Laravel Version

11.0.7

### PHP Version

8.3.4 ubuntu 22.04

### Description

I Have a bug : 
cURL error 56: OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
Error in : pusher-php-server/src/Pusher.php(776) post ok but error trigered !
PHP curl :
Libcurl : 7.81.0
OpenSSL : 3.0.2
I see similar problem , tried to changer curl config but nothing work.
I connect in websocket with wss + letsencrypt cert, pusherphpserver connect on https.

If my job $tries=3 it push the event 3 times ! So have to stay with 1 try, because the event is pushed, but the Job fail.

Tried a workaround : use http for pusher with 127.0.0.1 and wss + hostname for websocket.
Is is possible to have a wss server + http ?

Or any defaut config to change to fix this ssl problem ?
No problem with soketi and can't upgrade curl on ubuntu 22 LTS.

### Steps To Reproduce

Use ubuntu server with letsencrypt cert + php 8.3 ondrej ppa + apache + redis + horizon
Error on every broadcast request

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by driesvints** [comment]
Also try looking at some of the other issues on this repo.

**Comment by neoteknic** [comment]
not really same issue, tried many things and many support channel, nothing worked, it's a but with reverb but can be related to libcurl and openssl, maybe can be fixed with another default config.
