### ISSUE TITLE
Move connection parameters to phpunit env

### ISSUE THREAD

**Issue by ArthurPatriot** [laravel/reverb#132]
Hello guys. What you think about to move all connections parameters to phpunit env. For example, I want to test reverb on windows machine, windows doesn't support creating socket connection on `0.0.0.0`, I must use local ip. And now, I must add `host` parameter to each test where present `host`...

Will be easy to get this parameters from env (`$host`, `$port`, `$appId`). And code will be more clean and reusable. What you think?

**Comment by joedixon** [comment]
I think it's nice to have the option to spin up multiple servers on different hosts, but I don't think I'm against defaulting to the phpunit environment.

**Comment by joedixon** [comment]
Would welcome a PR for this, but closing for now.
