### ISSUE TITLE
Please mentioned that how to live reverb in apache server.

### ISSUE THREAD

**Issue by tarun-pixeleyez** [laravel/reverb#140]
Hello Team,

We have created one application using Laravel Reverb. Now we want to live it and not adea about how to do it in apache server so please add some basic information in documentation so its easy to do.

Thank You.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
