### ISSUE TITLE
WebSocket connection to 'wss://chat-laravel.mydomain.com:9889/app/oknjjl0bzpsq17de2ebn?protocol=7&client=js&version=8.4.0-rc2&flash=false' failed: 

### ISSUE THREAD

**Issue by raj3292** [laravel/reverb#141]
### Reverb Version

@beta

### Laravel Version

11.0

### PHP Version

8.2.10

### Description

I have an SSL certificate from Certbot and use the reverb@beta version. I am getting an error while connecting to the socket.
I am using an Apache Digital Ocean server. The port is added in the ufw apache. Let me know if anything wrong my side.

This is in my .env file

```
REVERB_APP_ID=898313
REVERB_APP_KEY="${REVERB_KEY}"
REVERB_APP_SECRET="${REVERB_SEC}"
REVERB_HOST=chat-laravel.mydomain.com
REVERB_HOSTNAME=chat-laravel.mydomain.com
REVERB_PORT=9889
REVERB_SCHEME=https
```

### Steps To Reproduce

Change port and start command using port & hostname but still facing the same issue.
I have rebuild and cleared the cache as well on every change.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by boris-glumpler** [comment]
I'm getting the same error, actually. I'm running Reverb with the `--debug` flag and am getting this error in the console:

```
Laravel\Reverb\Protocols\Pusher\Http\Controllers\PusherController::Laravel\Reverb\Protocols\Pusher\Http\Controllers\{closure}(): Argument #1 ($message) must be of type string, Ratchet\RFC6455\Messaging\Message given, called in .../app/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php on line 254

  at vendor/laravel/reverb/src/Protocols/Pusher/Http/Controllers/PusherController.php:34
```
