### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by vatsake** [laravel/reverb#146]
### Reverb Version

1.0.0-beta4

### Laravel Version

11.0.8

### PHP Version

8.2

### Description

#145 

### Steps To Reproduce

 1. Connect via postman
 2. Monitor memory usage
 3. Spam send ping events.

**Comment by driesvints** [comment]
You're 2 beta's behind. Please try the latest version and try posting on the Laracasts or laravel.io forums first. We currently don't have any other reports of a memory leak.

**Comment by driesvints** [comment]
If you have more specific steps to reproduce then definitely feel free to open a new issue.

**Comment by driesvints** [comment]
Can you post a new issue with a repo and detailed steps on how to reproduce?

```bash
laravel new bug-report --github="--public"
```
