### ISSUE TITLE
Starting in secure mode even if certificate is not specified

### ISSUE THREAD

**Issue by vatsake** [laravel/reverb#155]
### Reverb Version

1.0.0-beta6

### Laravel Version

11

### PHP Version

8.2

### Description

Am I understanding correctly, that if the certificate is not specified then it tries to grab it itself from "hostname"?

My app is behind a reverse proxy, that means the connection between proxy and app is not encrypted.
The websocket server is started in secure mode with wrong certificate.
```
    location /websocket {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http:/app:8080/;
    }
```

src/Servers/Reverb/Factory.php 114
```
    protected static function configureTls(array $context, ?string $hostname): array
    {
        $context = array_filter($context, fn ($value) => $value !== null);

        $usesTls = ($context['local_cert'] ?? false) || ($context['local_pk'] ?? false);

        if (! $usesTls && $hostname && Certificate::exists($hostname)) {
            [$certificate, $key] = Certificate::resolve($hostname);

            $context['local_cert'] = $certificate;
            $context['local_pk'] = $key;
        }

        return $context;
    }
```

You can close this issue if the first question is false.

### Steps To Reproduce

.

**Comment by joedixon** [comment]
Reverb will try to grab the certificate from the Valet or Herd paths using the `REVERB_HOST` value, but only if you are not manually specifying your own certifcate.

**Comment by joedixon** [comment]
That was fixed here: https://github.com/laravel/reverb/pull/85

Are you on the latest version?

**Comment by joedixon** [comment]
Can you do some logging in here and see where the certificate is being found?

https://github.com/laravel/reverb/blob/bf6b6f85cdc3fff360761dac9f854c27ffc792fe/src/Servers/Reverb/Factory.php#L114-L128

**Comment by joedixon** [comment]
Thanks @vatsake

Can you give this PR a try? https://github.com/laravel/reverb/pull/158

**Comment by joedixon** [comment]
Great minds think alike! Just pushed a fix
