### ISSUE TITLE
Send event and wait response

### ISSUE THREAD

**Issue by Atmden** [laravel/reverb#157]
Hello!
I need your help.
We are developing a mobile application.
We send an event to the mobile application and we need to receive a response to this event within a certain timeout; if the response is not received, we need to send another event to another channel.
Maybe there is another better solution
I kindly ask you to help me solve this problem.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
