### ISSUE TITLE
Add a way to know what is being used for event loop

### ISSUE THREAD

**Issue by cornzzy** [laravel/reverb#165]
Is there any way I can make sure the event loop extension is working? Or even better, add an env var to set the event loop extension and show error if it's inaccessible.

This part of the doc is quite challenging to me.
![image](https://github.com/laravel/reverb/assets/116248852/0df58bd1-4c7e-494b-9909-5cdab5620cc4)

**Comment by joedixon** [comment]
Hey @cornzzy, that's not something we have on the roadmap right now. You can check the extension is installed on your environment by running `php -m`. If any of the extensions are installed, Reverb will use it.
