### ISSUE TITLE
Allow Custom Prefix Specification for Laravel Reverb Socket Routes

### ISSUE THREAD

**Issue by kirills-morozovs** [laravel/reverb#168]
**Current Situation:**
In the existing codebase of Reverb, it's not feasible to designate a prefix to be added before Laravel Reverb socket implementation routes. This limitation poses challenges, particularly when trying to integrate Reverb with Kubernetes default Ingress, which doesn't support multiple ports with the same path and host.

**Proposed Solution:**
To mitigate these challenges and enhance flexibility, allow specification of a custom prefix for routes within the Laravel Reverb configuration.

**Comment by driesvints** [comment]
Hi there. Right now we don't have any plans for this sorry. If you want, you can always attempt a PR to see if it gets accepted.
