### ISSUE TITLE
realtime'websocket

### ISSUE THREAD

**Issue by lootnath** [laravel/reverb#171]
in case multimedia requires protocols and firewall allowing their dfunctioning, how would websocket allow constant funxtion thara realtime

**Comment by ahmsmith** [comment]
I believe that websockets would use a stun server to get each peers trace and presents ICE canidates. If the connection cannot be established via happy path. It will use a turn server to  as a media relay.

![image](https://github.com/laravel/reverb/assets/7451151/8c959b7e-e362-4a6b-9051-b8f2a3854a58)


![image](https://github.com/laravel/reverb/assets/7451151/f88f52b4-809d-4b8c-a878-184b96c65202)
