### ISSUE TITLE
Reverb + Valet SSL Certificate Issue: Unable to get local issuer certificate

### ISSUE THREAD

**Issue by hcancelik** [laravel/reverb#177]
### Reverb Version

1.0.0-beta9

### Laravel Version

11.4.0

### PHP Version

8.2.16

### Description

Valet Version:  4.6.1

Here is the env values.

```
REVERB_HOST="kc.test"
REVERB_PORT=8080
REVERB_SCHEME=https
```

Client can successfully connect to ws server however, when broadcasting events, the queue worker fails with exception.

```
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://kc.test:8080/apps/399641/events?auth_key=gdekqnlzpqvnrct6kpd5&auth_timestamp=1714296669&auth_version=1.0&body_md5=329aab1d9baef4764c3589db3d92c197&auth_signature=9e1dfc125c896a781dbdfb6605409121e63c4a830751cb9afc185d312f466361
```

![Screenshot 2024-04-28 at 12 36 24](https://github.com/laravel/reverb/assets/5788410/ea2a6fcb-0e67-4f5d-9281-21626b765e77)

Not sure if it's related but `https://kc.test:8080` returns not found.

### Steps To Reproduce

Using valet with latest valet, laravel and reverb version.

**Comment by hcancelik** [comment]
This is probably not an important issue. For some reason I was under impression that reverb needs to be run under https for local environment.

**Comment by P-James** [comment]
Would be keen to see this re-opened. I need https locally for browser permissions and have got this same issue
