### ISSUE TITLE
Reverb not sending any event to client

### ISSUE THREAD

**Issue by crazynds** [laravel/reverb#178]
### Reverb Version

v1.0.0-beta9

### Laravel Version

v11.5.0

### PHP Version

8.3.3

### Description

I have setup a basic project following the steps to configure reverb and their functionalities, but nothing I do work to send any event to the client listening in the socket. The event is dispatched, and the client socket is connected in the reverb:start server, but when I dispatch some event, the worker show that it work in this event but the reverb dont show anything (with --debug flag) that it has sended the event to the clients, the only output log is over time the ping sended and recived.

I created a [public repo](https://github.com/crazynds/ReverbTestLaravel) with just a base laravel configuration and reverb that I'm using for this test to create a simple application to broadcast a message to all connected clients.

I'm using windows 11 if that change anything.

### Steps To Reproduce

1. Create a clean laravel 11 project and add the basic auth ui and install:broadcast.

2. Create the following classes:

(Create the model Message with migrations, but not necessary to add the code in this issue)

Event:
```php
class GotMessage implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct(public array $message)
    {
        //
    }

    public function broadcastOn(): array
    {
        // $this->message is available here
        return [
            new PrivateChannel("channel_for_everyone"),
        ];
    }
}
```

Job: 
```php
class SendMessage implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct(public Message $message)
    {
        //
    }

    public function handle(): void
    {
        GotMessage::dispatch([
            'id' => $this->message->id,
            'user_id' => $this->message->user_id,
            'text' => $this->message->text,
            'time' => $this->message->time,
        ]);
    }
}

```

Command to create a job to dispatch an event:
```php
class Test extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:test';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $message = Message::create([
            'user_id' => User::query()->first()->id,
            'text' => 'mensagem to all',
        ]);
        SendMessage::dispatch($message);
    }
}
```

channels.php
```php
use Illuminate\Support\Facades\Broadcast;

Broadcast::channel('channel_for_everyone', function ($user) {
    return true;
});
```

In home.blade.php add the following script:
```html
    <script>
        window.addEventListener("load", function() {
            window.Echo.channel('channel_for_everyone')
                .listenToAll((event, data) => {
                    // do what you need to do based on the event name and data
                    console.log(event, data)
                })
        })
    </script>
```

3. Start the aplication:

php artisan serve
php artisan reverb:start --debug
php artisan queue:listen

4. Go to dashboard page (Register + login)

5. On this screen you can use f12 to see if the socket is connected:
![image](https://github.com/laravel/reverb/assets/36674096/6a81f163-937c-4391-893b-8011ce220515)

6. Run the command to send an event:

php artisan app:test

7. The event is not pushed to client.

* I have tried in some controller method and without the job and the result is the same. None event is pushed to client.

## My thoughts

I think that the event is probably not being sent to the thread that is executing reverb:start, but I don't know how the events are dispatched between threads (whether via cache, database, filesystem,...). Without knowing how events are dispatched, I can't debug what my error might be.

I actually tried to make an laravel application from scratch following several tutorials, including the one on the official Laravel YouTube page, and with none of them I managed to get the event distributed via broadcast.

I'm 99.9% sure that it could be my error, but I've already reread the documentation and haven't had any success. The documentation for using broadcast is also very confusing as it is divided into 3 ([Event Docs](https://laravel.com/docs/11.x/events), [Broadcast Docs](https://laravel.com/docs/11.x/broadcasting) and [Reverb Docs](https://laravel.com/docs/11.x/reverb)), and makes it difficult to know what I am doing wrong.

**Comment by sinnbeck** [comment]
You are broadcasting a private event (PrivateChannel) but you are listing on a public channel (Echo.channel())

Change PrivateChannel to Channel or change Echo.channel() to Echo.private()

**Comment by crazynds** [comment]
@sinnbeck
Replacing PrivateChannel to Channel doesnt seen to work either.

![image](https://github.com/laravel/reverb/assets/36674096/5df92b31-93cb-4931-a5e2-8d014218a4e6)

As you can see in the image, the reverb server didn't send any mensage after the subscribe, even when the GotMessage was dispatched after that.

And replacing `.channel` to `.private` the only different behaviour is when opened a connection the client didn't subricribe at any channel:
![image](https://github.com/laravel/reverb/assets/36674096/d92c0939-44b4-48f0-a582-c29db1e95c51)

I have found the repo of the laracast presentation of reverb. I will explore this repo and see if I can found whats wrong.

*sorry for the images, i couldn't copy these output to paste as text.

**Comment by joedixon** [comment]
It's not actually Reverb which handles that endpoint - it's part of the framework itself. Looks like that's why you're not able to auth with the private channel though.

Did you run the `install:broadcasting` command?

**Comment by crazynds** [comment]
> Did you run the `install:broadcasting` command?

Yes, if I run this command again this is the output.

```sh
$ php artisan install:broadcasting

   ERROR  The 'broadcasting' configuration file already exists.

   ERROR  Broadcasting routes file already exists.

  Would you like to install and build the Node dependencies required for broadcasting? (yes/no) [yes]
❯ no
```

> It's not actually Reverb which handles that endpoint - it's part of the framework itself. Looks like that's why you're not able to auth with the private channel though.

But one think I notice with this comment is that if I change my broadcast route to:
```php
Broadcast::channel('App.Models.User.{id}', function ($user, $id) {
    dd('ok');
    return (int) $user->id === (int) $id;
});
```
It didn't print the 'ok' debug message in the route /broadcast/auth.

If I execute the command `route:list` I get the /broadcast/auth route:
```
  GET|HEAD  / ............................................................................................................  
  POST      _ignition/execute-solution ..... ignition.executeSolution › Spatie\LaravelIgnition › ExecuteSolutionController  
  GET|HEAD  _ignition/health-check ................. ignition.healthCheck › Spatie\LaravelIgnition › HealthCheckController  
  POST      _ignition/update-config .............. ignition.updateConfig › Spatie\LaravelIgnition › UpdateConfigController  
  GET|POST|HEAD broadcasting/auth ............................. Illuminate\Broadcasting › BroadcastController@authenticate  
  GET|HEAD  confirm-password .................................. password.confirm › Auth\ConfirmablePasswordController@show  
  POST      confirm-password .................................................... Auth\ConfirmablePasswordController@store  
  GET|HEAD  dashboard .......................................................................................... dashboard  
  POST      email/verification-notification ....... verification.send › Auth\EmailVerificationNotificationController@store  
  GET|HEAD  forgot-password ................................... password.request › Auth\PasswordResetLinkController@create  
  POST      forgot-password ...................................... password.email › Auth\PasswordResetLinkController@store  
  GET|HEAD  login ..................................................... login › Auth\AuthenticatedSessionController@create  
  POST      login .............................................................. Auth\AuthenticatedSessionController@store  
  POST      logout .................................................. logout › Auth\AuthenticatedSessionController@destroy  
  PUT       password .................................................... password.update › Auth\PasswordController@update  
  GET|HEAD  podcasts ...................................................................................... podcasts.index  
  PUT       podcasts/{podcast}/publish .................................................................. podcasts.publish  
  GET|HEAD  profile ................................................................ profile.edit › ProfileController@edit  
  PATCH     profile ............................................................ profile.update › ProfileController@update  
  DELETE    profile .......................................................... profile.destroy › ProfileController@destroy  
  GET|HEAD  register ..................................................... register › Auth\RegisteredUserController@create  
  POST      register ................................................................. Auth\RegisteredUserController@store  
  POST      reset-password ............................................. password.store › Auth\NewPasswordController@store  
  GET|HEAD  reset-password/{token} .................................... password.reset › Auth\NewPasswordController@create  
  GET|HEAD  sanctum/csrf-cookie ........................ sanctum.csrf-cookie › Laravel\Sanctum › CsrfCookieController@show  
  GET|HEAD  up ...........................................................................................................  
  GET|HEAD  verify-email .................................... verification.notice › Auth\EmailVerificationPromptController  
  GET|HEAD  verify-email/{id}/{hash} .................................... verification.verify › Auth\VerifyEmailController  

                                                                                                       Showing [28] routes  

```

But I don't understand why, even when the broadcast is installed. 🤔

**Comment by crazynds** [comment]
Ok, now I get it, this is really my fault when I cloned the repo from laracast.
At my `.env` file: 
```
BROADCAST_CONNECTION=log
```

Should be:
```
BROADCAST_CONNECTION=reverb
```

This makes the response works. I only get this reading the source code of \Illuminate\Broadcasting\BroadcastController. Rereading the documentation of [broadcasting](https://laravel.com/docs/11.x/broadcasting) I notice the only one driver that dont tell to change the .env variable `BROADCAST_CONNECTION` is the Reverb, even in the [Reverb docs](https://laravel.com/docs/11.x/reverb), so that's probably why I didn't realize.

Thanks for the time! @joedixon @driesvints @sinnbeck

**Comment by crazynds** [comment]
Maybe this should be setted in the reverb:install command.

**Comment by joedixon** [comment]
The `BROADCAST_CONNECTION` variable does get set in the install command so not sure why that wasn't applied for you

https://github.com/laravel/reverb/blob/main/src/Console/Commands/InstallCommand.php#L173-L187

When I get some time, I will pull down that example repo and give it a try.

**Comment by rokde** [comment]
I have the same issue, even when the BROADCAST_CONNECTION has the value reverb. It does not work using php artisan serve. Can anybody help?

**Comment by iamvinny** [comment]
> The `BROADCAST_CONNECTION` variable does get set in the install command so not sure why that wasn't applied for you
> 
> https://github.com/laravel/reverb/blob/main/src/Console/Commands/InstallCommand.php#L173-L187
> 
> When I get some time, I will pull down that example repo and give it a try.

In my case it didn't get set because I deployed my project to production and when I did `cp .env.example .env` it was not included in the example env.

**Comment by muhammad-rizwan** [comment]
I tried it yesterday and when installing broadcasting, .env variables are created in .env but not in .env.example file.
