### ISSUE TITLE
I have issue in reverb broadcasting with Laravel Forge

### ISSUE THREAD

**Issue by rahmani-djamel** [laravel/reverb#184]
### Reverb Version

@beta

### Laravel Version

11.0

### PHP Version

8.3

### Description

I have a strange issue with reverb it works locally but it is not in production with no error log. I'm using Laravel Forge and this is my .env file

BROADCAST_DRIVER=reverb
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync

REVERB_HOST=ws.***.co
REVERB_PORT=443
REVERB_SCHEME="https"
REVERB_SERVER_PORT=8080

![websocket issue](https://github.com/laravel/reverb/assets/73309458/a219f2ef-abd8-46d2-a4f9-42d128ead55e)

but when I broadcast event  locally it show on my browser console but in live it didn't I check laravel telescope and I found the event so the issue in the the connection between echo and reverb 

how to fix that ?

### Steps To Reproduce

![reverb_issue](https://github.com/laravel/reverb/assets/73309458/1ef264dd-34a0-4b87-b0ce-167d4b2fa9ae)

**Comment by rahmani-djamel** [comment]
![more reverb](https://github.com/laravel/reverb/assets/73309458/f3e36cb7-8096-4648-a5cb-a013fceb7fa7)
![more1](https://github.com/laravel/reverb/assets/73309458/6cc39f06-281b-43cc-a297-9e074d8ce038)
![more2](https://github.com/laravel/reverb/assets/73309458/87809727-afa0-4168-aaf6-14c61dccbb3b)

   window.Echo.channel('upload.')
              .listen('.upload-completed', (event) => {
                  console.log(event);
                  console.log("success");
              });

I tested the connection in Postman and it worked 

```
{
    "event": "pusher:connection_established",
    "data": "{\"socket_id\":\"456890587.966221455\",\"activity_timeout\":30}"
}
```

which kind of information I can provide more

**Comment by joedixon** [comment]
Hey @rahmani-djamel do you see any errors in you application logs or failed jobs table?

**Comment by rahmani-djamel** [comment]
hi @joedixon  no errors in the console or in the log file I create a route to fire the event 

```
Route::get('/test-event', function () { 
    event(new \App\Events\UploadCompleted(1));
    return 'Event has been sent!';
});

and locally no errors and it works fine but In production 0 errors and not works

**Comment by joedixon** [comment]
On Laravel 11, I believe the broadcast environment variable should be `BROADCAST_CONNECTION=` rather than `BROADCAST_DRIVER=` as you have listed in your original post.

**Comment by rahmani-djamel** [comment]
yes that was exactly the issue thank you @joedixon

**Comment by LuisDavidNietoMejia** [comment]
Hello, I still had configuration problems but I followed the tutorial to create a separate server with nginx plus the other configurations that Laravel Forge offers and it worked... I had to downgrade both the Laravel echo package and the reverb package in the json package... so that it worked 100%

https://codecourse.com/articles/laravel-websockets-on-forge
