### ISSUE TITLE
Laravel Reverb with Octane

### ISSUE THREAD

**Issue by sibalonat** [laravel/reverb#192]
I have created a new project in my wsl environment. I thought to try and use Octane + FrankenPhp and Reverb since it there was a lot of discussion about it. 
My configuration so far is:
Laravel using docker octane and frankenphp.
in the supervisor, i run these two commands, among the commands for the serve: 
`[program:octane]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --host=localhost --port=443 --admin-port=2019 --https
user=root
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
command=php /var/www/html/artisan reverb:start
autostart=true
autorestart=true
user=%(ENV_SUPERVISOR_PHP_USER)s
redirect_stderr=true
minfds=10000
stdout_logfile=/var/www/html/storage/logs/reverb.log`

my env file i have this, also with the connection to reverb:
REVERB_APP_ID=secret
REVERB_APP_KEY=secret
REVERB_APP_SECRET=secret
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http 

And docker: 
laravel.test:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '443:443'
            - '443:443/udp'
            # - '${REVERB_SERVER_PORT:-8080}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            XDG_CONFIG_HOME:  /var/www/html/config
            XDG_DATA_HOME:  /var/www/html/data
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
   this setup allows me to run the localhost in https, so I can't put the files for the pem files in the configuration tls, and also I can't use the hostname parameter in the command because it would throw an error. Im currently using Octane and installed frankenphp through Octane. Is there a way to have a working example with one of the implementations in docker and https

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
