### ISSUE TITLE
could not find driver (Connection: mysql, SQL: select * from `cache` where `key` = laravel:reverb:restart limit 1)

### ISSUE THREAD

**Issue by rawezhcode** [laravel/reverb#196]
### Reverb Version

1.0.0-beta10

### Laravel Version

11

### PHP Version

8.3

### Description

`
   Illuminate\Database\QueryException 

  could not find driver (Connection: mysql, SQL: select * from `cache` where `key` = laravel:reverb:restart limit 1)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809â–•                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810â–•                 );
    811â–•             }
    812â–• 
  âžœ 813â–•             throw new QueryException(
    814â–•                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815â–•             );
    816â–•         }
    817â–•     }

      [2m+37 vendor frames [22m

  38  artisan:13
      Illuminate\Foundation\Application::handleCommand()
`
I've done everything a lot, everything is working fine now, but it shows this error in the log file

### Steps To Reproduce

`
   Illuminate\Database\QueryException 

  could not find driver (Connection: mysql, SQL: select * from `cache` where `key` = laravel:reverb:restart limit 1)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809â–•                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810â–•                 );
    811â–•             }
    812â–• 
  âžœ 813â–•             throw new QueryException(
    814â–•                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815â–•             );
    816â–•         }
    817â–•     }

      [2m+37 vendor frames [22m

  38  artisan:13
      Illuminate\Foundation\Application::handleCommand()
`

<img width="939" alt="SCR-20240514-lema" src="https://github.com/laravel/reverb/assets/53620168/9010916f-da76-482b-b12a-6a74330ddb4a">

**Comment by l3aro** [comment]
It seems you're persisting cache in database.
Laravel 11 offer using cache in database by default, with migration included like below

![image](https://github.com/laravel/reverb/assets/25253808/a542cefe-c629-4a25-8046-74fe518c988b)

So you have 2 options to solved that
1. Setup database connection then run the migration
2. Setup redis then change `CACHE_STORE` to `redis` (recommended)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
