### ISSUE TITLE
redis is empty

### ISSUE THREAD

**Issue by rawezhcode** [laravel/reverb#197]
### Reverb Version

1.0.0-beta10

### Laravel Version

11

### PHP Version

8.3

### Description

Now Ihave everything set up perfectly, but the only problem is that the data is not stored in redis server in ( digitalocean )
and is empty 

### Steps To Reproduce

`  'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
            'scheme'   => env('REDIS_SCHEME', 'tls'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],
`

`
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=reverb
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=xxxxxx
REDIS_USERNAME=default
REDIS_PASSWORD=xxxxxxxx
REDIS_PORT=25061
`

![SCR-20240514-ppas](https://github.com/laravel/reverb/assets/53620168/74bab74c-8aa1-4a7b-b472-48afa1b25684)

![SCR-20240514-pqgg](https://github.com/laravel/reverb/assets/53620168/f82f9dc7-d5a9-4a7f-8f37-082384103a1f)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MarcelM1109** [comment]
I got the same issue. When i start Reverb with the config i get no error but redis stays empty. Did you managed to find a solution?
