### ISSUE TITLE
Reverb on Subdomain can't initiate websocket server

### ISSUE THREAD

**Issue by groxw** [laravel/reverb#198]
### Reverb Version

@beta

### Laravel Version

11.6.0

### PHP Version

8.2

### Description

I'm having trouble with the laravel reverb wobsocket connection. Surprisingly in my problem, laravel reverb can work fine when I visit a site with a port for laravel reverb. 

But if I don't visit the site then there is a problem with the details: 

WebSocket connection to '
wss://sub.domain.com:9021/app/swjcj9gqljmwyquj4934?protocol=7&client=js&version=8.4.0-rc2&flash=false'
' failed 

But when I visit sub.domain.com:9021 in a new tab, laravel reverb works.

Here's my .env 

```
REVERB_APP_ID=*
REVERB_APP_KEY=*
REVERB_APP_SECRET=*
REVERB_HOST="sub.domain.com"
REVERB_PORT=443
REVERB_SCHEME=https

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT=9021
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

my nginx 
```
location / {
        proxy_cache $CPANEL_PROXY_CACHE;
        proxy_no_cache $CPANEL_SKIP_PROXY_CACHING;
        proxy_cache_bypass $CPANEL_SKIP_PROXY_CACHING;

        proxy_cache_valid 200 301 302 60m;
        proxy_cache_valid 404 1m;
        proxy_cache_use_stale error timeout http_429 http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
        proxy_cache_revalidate on;
        proxy_cache_min_uses 1;
        proxy_cache_lock off;



        include conf.d/includes-optional/cpanel-proxy.conf;
        proxy_pass $CPANEL_APACHE_PROXY_PASS;
    }

    location /app {


        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_pass http://0.0.0.0:9021;


    }

```

### Steps To Reproduce

- Make sure the server port is open and authorized by the firewall
- websocket with wss protocol in SSL
- certificate path
- I have tried to equalize REVERB_PORT and VITE_REVERB_PORT with the same value, but the error is still there.

Is there any solution to solve my problem?

**Comment by joedixon** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

    [Laracasts Forums](https://laracasts.com/discuss)
    [Laravel.io Forums](https://laravel.io/forum)
    [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
    [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
    [Larachat](https://larachat.co/)
    [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by niravswami** [comment]
@groxw I am facing the same issue. Did you find a solution?
