### ISSUE TITLE
Reverb not connectable locally via WebSocket (404)

### ISSUE THREAD

**Issue by medero** [laravel/reverb#202]
### Reverb Version

v1.0.0-beta10

### Laravel Version

11.7.0

### PHP Version

8.3.7

### Description
I tried creating a fresh laravel project to reproduce and upon starting reverb with the defaults (0.0.0.0:8080) it gives a 404 GET on Chrome/Firefox even overriding the host with 127.0.0.1 or such. Alternatively tried node with ipv4/ipv6 and those both reliably work and return a 101.

Even with the --debug flag to start reverb there's nothing in laravel logs. Artisan successfully starts and I can see the "Welcome" page on port 8000 (web port) so Laravel seems to work at a base level, just not reverb.

When reverb is not running, I get `NS_ERROR_CONNECTION_REFUSED`. With a bogus host, I get `NS_ERROR_UNKNOWN_HOST`

When reverb is running I get a 404, so it means it's still hitting Laravel.

<img width="938" alt="Screen Shot 2024-05-21 at 1 32 37 AM" src="https://github.com/laravel/reverb/assets/29695/23029026-ec8f-4245-a307-22fc848834b4">
<img width="944" alt="Screen Shot 2024-05-21 at 1 35 32 AM" src="https://github.com/laravel/reverb/assets/29695/b8f5f415-c489-4ebf-8c0c-e2f237dff313">

Just to sanity check, .env has these values by default (cleared out app id, app key, app secret):

```
BROADCAST_CONNECTION=reverb
REVERB_APP_ID=
REVERB_APP_KEY=
REVERB_APP_SECRET=
REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http
```

broadcasting.php:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Broadcaster
    |--------------------------------------------------------------------------
    |
    | This option controls the default broadcaster that will be used by the
    | framework when an event needs to be broadcast. You may set this to
    | any of the connections defined in the "connections" array below.
    |
    | Supported: "reverb", "pusher", "ably", "redis", "log", "null"
    |
    */

    'default' => env('BROADCAST_CONNECTION', 'null'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over WebSockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [

        'reverb' => [
            'driver' => 'reverb',
            'key' => env('REVERB_APP_KEY'),
            'secret' => env('REVERB_APP_SECRET'),
            'app_id' => env('REVERB_APP_ID'),
            'options' => [
                'host' => env('REVERB_HOST'),
                'port' => env('REVERB_PORT', 443),
                'scheme' => env('REVERB_SCHEME', 'https'),
                'useTLS' => env('REVERB_SCHEME', 'https') === 'https',
            ],
            'client_options' => [
                // Guzzle client options: https://docs.guzzlephp.org/en/stable/request-options.html
            ],
        ],

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => env('PUSHER_HOST') ?: 'api-'.env('PUSHER_APP_CLUSTER', 'mt1').'.pusher.com',
                'port' => env('PUSHER_PORT', 443),
                'scheme' => env('PUSHER_SCHEME', 'https'),
                'encrypted' => true,
                'useTLS' => env('PUSHER_SCHEME', 'https') === 'https',
            ],
            'client_options' => [
                // Guzzle client options: https://docs.guzzlephp.org/en/stable/request-options.html
            ],
        ],

        'ably' => [
            'driver' => 'ably',
            'key' => env('ABLY_KEY'),
        ],

        'log' => [
            'driver' => 'log',
        ],

        'null' => [
            'driver' => 'null',
        ],

    ],

];
```

And reverb.php has allowed origins set to *:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Reverb Server
    |--------------------------------------------------------------------------
    |
    | This option controls the default server used by Reverb to handle
    | incoming messages as well as broadcasting message to all your
    | connected clients. At this time only "reverb" is supported.
    |
    */

    'default' => env('REVERB_SERVER', 'reverb'),

    /*
    |--------------------------------------------------------------------------
    | Reverb Servers
    |--------------------------------------------------------------------------
    |
    | Here you may define details for each of the supported Reverb servers.
    | Each server has its own configuration options that are defined in
    | the array below. You should ensure all the options are present.
    |
    */

    'servers' => [

        'reverb' => [
            'host' => env('REVERB_SERVER_HOST', '0.0.0.0'),
            'port' => env('REVERB_SERVER_PORT', 8080),
            'hostname' => env('REVERB_HOST'),
            'options' => [
                'tls' => [],
            ],
            'max_request_size' => env('REVERB_MAX_REQUEST_SIZE', 10_000),
            'scaling' => [
                'enabled' => env('REVERB_SCALING_ENABLED', false),
                'channel' => env('REVERB_SCALING_CHANNEL', 'reverb'),
                'server' => [
                    'url' => env('REDIS_URL'),
                    'host' => env('REDIS_HOST', '127.0.0.1'),
                    'port' => env('REDIS_PORT', '6379'),
                    'username' => env('REDIS_USERNAME'),
                    'password' => env('REDIS_PASSWORD'),
                    'database' => env('REDIS_DB', '0'),
                ],
            ],
            'pulse_ingest_interval' => env('REVERB_PULSE_INGEST_INTERVAL', 15),
            'telescope_ingest_interval' => env('REVERB_TELESCOPE_INGEST_INTERVAL', 15),
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Reverb Applications
    |--------------------------------------------------------------------------
    |
    | Here you may define how Reverb applications are managed. If you choose
    | to use the "config" provider, you may define an array of apps which
    | your server will support, including their connection credentials.
    |
    */

    'apps' => [

        'provider' => 'config',

        'apps' => [
            [
                'key' => env('REVERB_APP_KEY'),
                'secret' => env('REVERB_APP_SECRET'),
                'app_id' => env('REVERB_APP_ID'),
                'options' => [
                    'host' => env('REVERB_HOST'),
                    'port' => env('REVERB_PORT', 443),
                    'scheme' => env('REVERB_SCHEME', 'https'),
                    'useTLS' => env('REVERB_SCHEME', 'https') === 'https',
                ],
                'allowed_origins' => ['*'],
                'ping_interval' => env('REVERB_APP_PING_INTERVAL', 60),
                'max_message_size' => env('REVERB_APP_MAX_MESSAGE_SIZE', 10_000),
            ],
        ],

    ],

];
```

System details:
- Mac M1
- composer 2.7.2
- PHP installed via brew
- No docker, no vagrant for this setup locally (no proxy/server config)
- No SSL setup locally, just running artisan serve and reverb:start

### Steps To Reproduce

**Laravel steps to reproduce:**

1. `composer create-project laravel/laravel test-websocket ^11.0`
2. `cd test-websocket`
3. `php artisan install:broadcasting`

<img width="926" alt="Screen Shot 2024-05-21 at 1 19 16 AM" src="https://github.com/laravel/reverb/assets/29695/9998d39a-0c22-4348-8974-d2c4ca4706e2">
<img width="926" alt="Screen Shot 2024-05-21 at 1 19 16 AM" src="https://github.com/laravel/reverb/assets/29695/df3a9c3e-dd47-49c1-85d1-1b8a4ab48092">

Would you like to install Laravel Reverb? [Yes]

Would you like to install and build the Node dependencies required for broadcasting? [Yes]

5. Before I run reverb:start, I check that 8080 isn't in use with `lsof -i :8080`
6. `php artisan reverb:start --debug`

   INFO  Starting server on 0.0.0.0:8080 (localhost).  

<img width="412" alt="Screen Shot 2024-05-21 at 1 27 34 AM" src="https://github.com/laravel/reverb/assets/29695/a4a49cc2-8ddf-4f0d-9444-fc0faad49cfc">

7. Now, `lsof -i :8080` reports that php is listening on a TCP 8080 port:

`php     **PID** meder    **FDVALUE**  IPv4 **DEVICEID**      0t0  TCP *:http-alt (LISTEN)
`

In Chrome and Firefox:

I get:

<img width="1501" alt="Screen Shot 2024-05-21 at 12 45 26 AM" src="https://github.com/laravel/reverb/assets/29695/0f23d534-80f5-490e-9ff3-b43c0360a635">

In Firefox's network tab:
<img width="380" alt="Screen Shot 2024-05-21 at 12 53 24 AM" src="https://github.com/laravel/reverb/assets/29695/9acf148e-1474-41d2-b550-b084cadb660d">

**Working node alternative with ipv6 and ipv4:**

```
// server.js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

console.log('WebSocket server is running on ws://0.0.0.0:8080');
```

Which lsof -i :8080 confirms node is listening on the 8080 TCP port:
`node    **PID** meder   **FDVALUE**  IPv6 **DEVICEID**      0t0  TCP *:http-alt (LISTEN)
`
I get a 101 response:

<img width="386" alt="Screen Shot 2024-05-21 at 12 54 30 AM" src="https://github.com/laravel/reverb/assets/29695/065916ba-4704-464b-94e5-30b22d5e4340">

Shortly after seeing the lsof output I saw ipv4 php used and ipv6 node used, to which I matched node and it still works, via:

```
const WebSocket = require('ws');

const server = new WebSocket.Server({ host: '127.0.0.1', port: 8080 }, () => {
  console.log('WebSocket server is listening on ws://127.0.0.1:8080');
});
```

`node    **PID** meder   **FDVALUE**  IPv4 **DEVICEID**      0t0  TCP localhost:http-alt (LISTEN)`

Screenshot:
<img width="1282" alt="Screen Shot 2024-05-21 at 1 57 03 AM" src="https://github.com/laravel/reverb/assets/29695/d36beb47-2441-4e52-873a-7a6b23d3862c">

**Attempt specifying php artisan reverb:start --host=127.0.0.1 didn't work either**

**Creating a test controller for a 200 OK/green path worked**
```
php artisan make:controller WebSocketTestController

class WebSocketTestController extends Controller
{
    public function test()
    {
        return response()->json(['message' => 'WebSocket test endpoint']);
    }
}
```

To rule out application wide 404 issues:

```
curl http://localhost:8000/websocket-test

{"message":"WebSocket test endpoint"}
```

**Comment by joedixon** [comment]
To confirm, have you cleared out the following `REVERB_` prefixed enviroment variables just for the purposes of not wanting to give away any sensitive information in the issue, or are they also empty in your app?

```
REVERB_APP_ID=
REVERB_APP_KEY=
REVERB_APP_SECRET=
```

**Comment by medero** [comment]
Correct. Actually, I think I found the issue in that it's hitting the 404 in vendor/laravel/reverb/src/Servers/Reverb/Http/Router.php:53:

```
    /**
     * Dispatch the request to the appropriate controller.
     */
    public function dispatch(RequestInterface $request, Connection $connection): mixed
    {
        $uri = $request->getUri();
        $context = $this->matcher->getContext();

        $context->setMethod($request->getMethod());
        $context->setHost($uri->getHost());

        try {
            $route = $this->matcher->match($uri->getPath());
        } catch (MethodNotAllowedException $e) {
            return $this->close($connection, 405, 'Method not allowed.', ['Allow' => $e->getAllowedMethods()]);
        } catch (ResourceNotFoundException $e) {
                    Log::error('Resource not found for URI: ' . $uri->getPath(), [
                        'uri' => $uri->getPath(),
                        'host' => $uri->getHost(),
                        'method' => $request->getMethod(),
                    ]);
            return $this->close($connection, 500, 'Not found!!!!!.');
        }
```

I added the above Log::error and this is the log:

[2024-05-21 09:25:27] local.ERROR: Resource not found for URI: / {"uri":"/","host":"localhost","method":"GET"}

Is this because it binds to specific routes that I'm missing beyond the base setup, or?

**Comment by medero** [comment]
Ah, I have to do an app specific call, eg `new WebSocket('localhost:8080/app/[app_id]')`

**Comment by joedixon** [comment]
Hey @medero that's right. You need to tell the Reverb server which app you wish to connect to.

**Comment by POMXARK** [comment]
https://beyondco.de/docs/laravel-websockets/advanced-usage/custom-websocket-handlers

I'm also looking for a way to set up a similar classic access point. and I don’t understand how to connect an external frontend to a channel without ws:// wss:/// and how to test it in postman

**Comment by Jesse-Dan** [comment]
'{"event": "pusher:subscribe", "data": {"channel": "test-c"}}'

@POMXARK use this to subscribe first and then set broadcasts
