### ISSUE TITLE
vite and reverb scheme is http on production but still sending wss

### ISSUE THREAD

**Issue by aftabkhaliq86** [laravel/reverb#208]
### Reverb Version

@beta

### Laravel Version

11

### PHP Version

8.2

### Description

   soccket is trying to connect with  wss  instead of ws |
   in env  my pusher and revert scheme is set to http
   but my site is secure using https
   is there anywas that when website is in https and scheme set to http it should connect with ws:/
   
   
![image](https://github.com/laravel/reverb/assets/129963183/e085c822-95a1-4ea4-a3f2-925d0af4f225)

because am using cpnael apache  and lets encrypt ssl 
if i add private &  publc key to a specific file to make it work with  ssl  
in browser i get this when i hit this url 

https://help.changer4u.com:8080/app/2ur0etpghgqsfvwbdllm?protocol=7&client=js&version=8.4.0-rc2&flash=false

![image](https://github.com/laravel/reverb/assets/129963183/7da61e4f-530c-43f2-b492-f3e2cc53ef03)
 and if i cancel this promt   connect work but thats not the solution i guess 

### Steps To Reproduce

   soccket is trying to connect with  wss  instead of ws |
   in env  my pusher and revert scheme is set to http
   but my site is secure using https
   is there anywas that when website is in https and scheme set to http it should connect with ws:/

**Comment by joedixon** [comment]
I'm afraid if the page you are connecting to the Reverb server from is served over HTTPS, the Pusher SDK (used under the hood by Echo), will force secure WebSockets (wss).

**Comment by aftabkhaliq86** [comment]
i am able to made conection with reverb  but during broadcasting message am getting this error now 
![image](https://github.com/laravel/reverb/assets/129963183/0f9f6293-9b2c-4475-b9f9-564ea4596222)

**Comment by joedixon** [comment]
Can you try running the server with the `--debug` option and seeing if there is any error reported?

**Comment by abrhamsw** [comment]
> ### Reverb Version
> @beta
> 
> ### Laravel Version
> 11
> 
> ### PHP Version
> 8.2
> 
> ### Description
> soccket is trying to connect with wss instead of ws | in env my pusher and revert scheme is set to http but my site is secure using https is there anywas that when website is in https and scheme set to http it should connect with ws:/
> 
> ![image](https://private-user-images.githubusercontent.com/129963183/338117979-e085c822-95a1-4ea4-a3f2-925d0af4f225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDk5ODAsIm5iZiI6MTcxOTY0OTY4MCwicGF0aCI6Ii8xMjk5NjMxODMvMzM4MTE3OTc5LWUwODVjODIyLTk1YTEtNGVhNC1hM2YyLTkyNWQwYWY0ZjIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwODI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmRlZjcwMmFiZGZhMDk3MzUzNWIyODMwNjA5OTA5NDY5NDViODg0OGI0NWE3YzgwODNjMmI4MDhiYjVkYjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HMCmta-GM8Be-uClBjrAJti0H-apoQ2DqDn30S1Vvog)
> 
> because am using cpnael apache and lets encrypt ssl if i add private & publc key to a specific file to make it work with ssl in browser i get this when i hit this url
> 
> https://help.changer4u.com:8080/app/2ur0etpghgqsfvwbdllm?protocol=7&client=js&version=8.4.0-rc2&flash=false
> 
> ![image](https://private-user-images.githubusercontent.com/129963183/338118835-7da61e4f-530c-43f2-b492-f3e2cc53ef03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDk5ODAsIm5iZiI6MTcxOTY0OTY4MCwicGF0aCI6Ii8xMjk5NjMxODMvMzM4MTE4ODM1LTdkYTYxZTRmLTUzMGMtNDNmMi1iNDkyLWYzZTJjYzUzZWYwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQwODI4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjNhZDBmNTJiZDdkN2UzZmFlM2E0YzhjYmVjZTgzNDYyMTk2ZmFhMTJjZmQxNzU5NmVmZWE0NzM1NDhhYWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.auDb50yq1XDJB_-kt0I_oaiaGYz04rjHdF24q5Thq0g) and if i cancel this promt connect work but thats not the solution i guess
> 
> ### Steps To Reproduce
> soccket is trying to connect with wss instead of ws | in env my pusher and revert scheme is set to http but my site is secure using https is there anywas that when website is in https and scheme set to http it should connect with ws:/

Can you share your Proxy Configuration? It is not working on my side, am using cpnael apache and lets encrypt ssl

**Comment by aftabkhaliq86** [comment]
@abrhamsw  to configure it on  panel using  lets encrypt follow these configurations
env
BROADCAST_DRIVER=reverb
BROADCAST_CONNECTION=reverb

in your broadcasting.php file in config folder add these

     'reverb' => [
            'driver' => 'reverb',
            'key' => env('REVERB_APP_KEY'),
            'secret' => env('REVERB_APP_SECRET'),
            'app_id' => env('REVERB_APP_ID'),
            'options' => [
                'host' => env('REVERB_HOST'),
                'port' => env('REVERB_PORT', 443),
                'scheme' => 'https',
                'useTLS' => 'true',
                 'curl_options' => [
             'CURLOPT_SSL_VERIFYHOST' => 0,
             'CURLOPT_SSL_VERIFYPEER' => 0,
         ],
            ],
            'client_options' => [
                // Guzzle client options: https://docs.guzzlephp.org/en/stable/request-options.html
               'verify' => false,
                ],
            ],
            
            
            in config folder add these  in reverb.php 
                'servers' => [

        'reverb' => [
            'host' => env('REVERB_SERVER_HOST', '0.0.0.0'),
            'port' => env('REVERB_SERVER_PORT', 8080),
            'hostname' => env('REVERB_HOST'),
            'options' => [
                'tls' => [
                    'local_cert' => env('REVERB_LOCAL_CERT',null),
                    'local_pk' => env('REVERB_LOCAL_PK',null),
                            'passphrase' => null,
                            'verify_peer'=>false,
                            'verify_peer_name'=>false,
                    ],
            ],
            'max_request_size' => env('REVERB_MAX_REQUEST_SIZE', 10_000),
            'scaling' => [
                'enabled' => env('REVERB_SCALING_ENABLED', false),
                'channel' => env('REVERB_SCALING_CHANNEL', 'reverb'),
                'server' => [
                    'url' => env('REDIS_URL'),
                    'host' => env('REDIS_HOST', '127.0.0.1'),
                    'port' => env('REDIS_PORT', '6379'),
                    'username' => env('REDIS_USERNAME'),
                    'password' => env('REDIS_PASSWORD'),
                    'database' => env('REDIS_DB', '0'),
                ],
            ],
            'pulse_ingest_interval' => env('REVERB_PULSE_INGEST_INTERVAL', 15),
            'telescope_ingest_interval' => env('REVERB_TELESCOPE_INGEST_INTERVAL', 15),
        ],

    ],
    
    
    for these values
      'local_cert' => env('REVERB_LOCAL_CERT',null),
                    'local_pk' => env('REVERB_LOCAL_PK',null),
                    
                    
                    go to SSL/tls status select domain and copy public and private key put them in separate files and add their path 
                    
                    happy coding

**Comment by abrhamsw** [comment]
> Proxy

Thank You, but how about Reverse Proxy configuration for Apache

**Comment by aftabkhaliq86** [comment]
> > Proxy
> 
> Thank You, but how about Reverse Proxy configuration for Apache

just follow these instructions on apache you don't need a proxy ...
