### ISSUE TITLE
"Data decoding error." on laravel + reverb websocket. Error message return after dispatch

### ISSUE THREAD

**Issue by awie214** [laravel/reverb#215]
### Reverb Version

@beta

### Laravel Version

11.0

### PHP Version

8.2

### Description

Succesfully setup laravel and reverb in web server. Reverb also running. But when I send message to other user the dispatch returns "Data decoding error".

### Steps To Reproduce

.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
