### ISSUE TITLE
set env variables for 'activity_timeout'

### ISSUE THREAD

**Issue by NVD-R** [laravel/reverb#217]
Hi, Can you read 'activity_timeout' from env variables?
i need increase this and its force me to 30 sec!

**Comment by joedixon** [comment]
You should be able to pass `activityTimeout` when initializing Echo.

**Comment by NVD-R** [comment]
Yes, but only for values ​​less than 30 seconds.
If you set mor than 30 sec Pusher-js get this value from server so max value can be 30 sec.
This cant be hard-code
