### ISSUE TITLE
Cannot access dashboard

### ISSUE THREAD

**Issue by nicolasvahidzein** [laravel/reverb#228]
### Reverb Version

v1.0.0-beta14

### Laravel Version

11.19

### PHP Version

8.2.21

### Description

Hello everyone,

I cannot seem to access the laravel dashboard.

Here are my env settings
```
REVERB_SERVER_PORT=8098
REVERB_APP_ID=xxx
REVERB_APP_KEY=yyy
REVERB_APP_SECRET=zzz
REVERB_HOST=127.0.0.1
REVERB_PORT=6001
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

should i be using IPOFMYSERVER:6001/dashboard or IPOFMYSERVER:8098/dashboard ?

i am using SElinux btw.

I see port 6001 running when i run this command: netstat -tuplen

but not the port for the server 8098.

I would love some help. Thanks.

### Steps To Reproduce

not sure how to reproduce. It is a vanilla install.

**Comment by nicolasvahidzein** [comment]
BTW it is an AlmaLinux v8 install with just the server CLI so i cannot test on the machine itself, i have to access it from the local network.

**Comment by joedixon** [comment]
> I cannot seem to access the laravel dashboard.

Can you elaborate on what you mean by the "laravel dashboard"?

**Comment by nicolasvahidzein** [comment]
sorry the laravel reverb dashboard. The one where you can see the activity of the websocket server.

**Comment by joedixon** [comment]
The Reverb dashboard is a via an integration with Laravel Pulse. Have you followed the instructions here?

https://laravel.com/docs/11.x/reverb#monitoring

**Comment by nicolasvahidzein** [comment]
Thank you so much. I somehow missed this.
