### ISSUE TITLE
Laravel Reverb not connecting, everytime I make changes

### ISSUE THREAD

**Issue by Kendaichi** [laravel/reverb#234]
### Reverb Version

"laravel/reverb": "v1.0.0@beta",

### Laravel Version

11.8.0

### PHP Version

8.3.7

### Description

I just tried laravel reverb, and I noticed that everytime I make some changes in the code, I can't connect to the websocket.

I returned the code back to where I started, but I still can't connect to the websocket. Please do take note that this was working flawlessly when I started.

I checked on the laravel documentation, it said to use this command

php artisan reverb:restart
To reflect the changes. but this doesn't seem working out for me.

### Steps To Reproduce

I added new public channel:

Broadcast::channel('ewpChanges', function () { return true; });

Then created an event:

class ewpChangesEvent implements ShouldBroadcast { use Dispatchable, InteractsWithSockets, SerializesModels;

 /**
  * Create a new event instance.
  */
 public function __construct(public array $data)
 {
     //
 }

 /**
  * Get the channels the event should broadcast on.
  *
  * @return array<int, \Illuminate\Broadcasting\Channel>
  */
 public function broadcastOn(): array
 {
     return [
         new Channel('ewpChanges'),
     ];
 }
}

Then suddenly I can't connect to the websocket

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Kendaichi** [comment]
Upon debugging further, I found out that the issue only persists on my Brave Browser. Now I am using chrome just to test the realtime functionality of the application I am making.
