### ISSUE TITLE
Subscribe and Unsubscribe Event 

### ISSUE THREAD

**Issue by AAmeriyan** [laravel/reverb#243]
We have been using laravel-websocket for many years and it was good for many purposes but now migrating to reverb confused me how can get each user subscribe and unsubscribe hook or event to add some logic to it?
for more detail we are holding each user online duration with laravel-websocket but i did not find any useful  detail about  this purposes

**Comment by driesvints** [comment]
Please see many closed issues and PR's about this one.

**Comment by AAmeriyan** [comment]
i could not find anything related to my need, why this important part of Websocket is missing in document?
