### ISSUE TITLE
PrivateChannels will not work with uuid (string) type id

### ISSUE THREAD

**Issue by TylerByte666** [laravel/reverb#247]
### Reverb Version

1.3.0

### Laravel Version

11.14.0

### PHP Version

8.3.11

### Description

My user's table uses *uuid* (string) as it's id field and not integers.

It seems the private channel always returns [HTTP/1.1 404 Not Found] even if the user id is correct.

I'm not sure if I missed something to get reverb to work in my current project. The project structure is generic.
I have tried a fresh project without using *uuid* and *string* type id fields and the error goes away. Can you please help?

### Steps To Reproduce

Here is an extract from my User model:

```php
class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasUuids;
    use Notifiable;
    use TwoFactorAuthenticatable;

    // Define the primary key type as UUID
    protected $keyType = 'string';

    // Indicate that the IDs are not auto-incrementing
    public $incrementing = false;

}
   ```
   
   Here is the *channels.php* file:
```php
Broadcast::channel('App.Models.User.{id}', function ($user, $id) {
    return (string) $user->id === (string) $id;
});
```

Here is the fronted view that listens for the events (userId is passed from controller):
```js
const props = defineProps({
    userId: String,
});

onMounted(() => {
  window.Echo.private(`App.Models.User.${props.userId}`)
      .listen('TestEvent', (event) => {
          console.log(event);
      });
});
```

The result:
Request url = http://localhost/broadcasting/auth
Request payload =
```
socket_id is correct "id"

channel_name is correct "private channel namespace"

```

Response in console on Browser:
```
[HTTP/1.1 404 Not Found]
```

**Comment by joedixon** [comment]
The `broadcasting/auth` endpoint is exposed by the framework and not by Reverb. Do you have [broadcasting enabled](https://laravel.com/docs/11.x/broadcasting#configuration) in your application?

**Comment by TylerByte666** [comment]
Hi yes that was done by the book, everything else except private channels is working. But I was able to prove that changing the id field to uuid did not break it so I am closing this issue. Sorry for wasting your time!
