### ISSUE TITLE
Pusher Unsubscribe Event is never triggered

### ISSUE THREAD

**Issue by mrfelipemartins** [laravel/reverb#250]
### Reverb Version

1.3.0

### Laravel Version

11.23.5

### PHP Version

8.3

### Description

Hello!

I am encountering an issue where the `pusher:unsubscribe` event is not being triggered when a user disconnects. I need to listen for this event through the MessageReceived event, but it never fires when a user leaves the connection.

To verify, I tested this behavior on a fresh Laravel installation and still experienced the same problem. Below are the relevant logs captured from the Reverb command output for additional context:

```
Connection Established ....................................................................................................... 870132037.115391333  
  Message Received ............................................................................................................. 870132037.115391333  
  
   1▕ { 
   2▕     "event": "pusher:subscribe", 
   3▕     "data": { 
   4▕         "auth": "mldn5cttj9l52bosbc8g:0abf97c88134fec78ceba8909c56f01f9674c89a8a03a791256c90b843041914", 
   5▕         "channel_data": { 
   6▕             "user_id... 

  Broadcasting To ................................................................................................................ presence-presence  
  
   1▕ { 
   2▕     "event": "pusher_internal:member_added", 
   3▕     "data": { 
   4▕         "user_id": "1", 
   5▕         "user_info": { 
   6▕             "id": 1, 
   7▕             "name": "John Doe", 
   8▕             "email": "johndoe@gmail.com... 

  Message Handled .............................................................................................................. 870132037.115391333  
  Broadcasting To ................................................................................................................ presence-presence  
  
   1▕ { 
   2▕     "event": "pusher_internal:member_removed", 
   3▕     "data": { 
   4▕         "user_id": "1" 
   5▕     }, 
   6▕     "channel": "presence-presence" 
   7▕ } 

  Connection Closed ............................................................................................................ 870132037.115391333 
  ```

As shown in the logs, while the pusher:subscribe event is present, the corresponding pusher:unsubscribe event does not seem to be triggered when the user disconnects, despite the connection being closed. 

### Steps To Reproduce

Here is an example repository where you can reproduce the issue:

https://github.com/mrfelipemartins/reverb-test

**Comment by joedixon** [comment]
The `pusher:unsubscribe` event should come from the client in the same way the `pusher:subscribe` event does. It sounds like your client is not sending the event?

**Comment by mrfelipemartins** [comment]
@joedixon I was wondering if the event should be triggered when the tab or browser is closed, or if there’s a better way to detect when a user has disconnected from my presence channel. I’ve been relying on the MessageReceived event, but it doesn’t seem to capture scenarios where the connection is unexpectedly interrupted, like when the browser is closed or the internet connection is lost. In these cases, I don’t receive the pusher:unsubscribe event.

Ideally, I’d like to use the pusher_internal:member_removed event to detect disconnections, but since this event isn’t sent through MessageReceived, I’m not sure how to implement it in this context. Do you have any suggestions on how best to handle this?

**Comment by mrfelipemartins** [comment]
@joedixon Thanks for the clarification!

If I were to submit a PR adding support for events such as:

```
public function close(Connection $connection): void
    {
        $this->channels
            ->for($connection->app())
            ->unsubscribeFromAll($connection);

        $connection->disconnect();

        Log::info('Connection Closed', $connection->id());

        ConnectionClosed::dispatch($connection); // <-- this event 
    }
```

and

```
public function open(Connection $connection): void
    {
        try {
            $this->verifyOrigin($connection);

            $connection->touch();

            $this->handler->handle($connection, 'pusher:connection_established');

            Log::info('Connection Established', $connection->id());

            ConnectionEstablished::dispatch($connection); // <-- this event
        } catch (Exception $e) {
            $this->error($connection, $e);
        }
    }
```
which would allow me to listen for these events in my application, would Reverb support and approve this addition?

**Comment by mrfelipemartins** [comment]
Hi @joedixon! Sorry to bring this up again, but I was wondering if I could get some closure on the subject above. The implementation would be very beneficial to several of my projects, and I believe it could help others as well.
