### ISSUE TITLE
Server logs: "Connection Established" but client does not receive pusher:connection_established

### ISSUE THREAD

**Issue by j-oppenhuis** [laravel/reverb#257]
### Reverb Version

1.4.1

### Laravel Version

11.27.2

### PHP Version

8.3.12

### Description

When changing Laravel Websockets from Beyondco to Laravel Reverb. I have the problem described in the title: Laravel reverb logs "Connection Established" but the client does not receive this. After some time the client will give a "WebSocket was closed before the connection was established" error. The Laravel Reverb server does not seem to throw an error of some kind. It just logs that the "Connection Closed".

### Steps To Reproduce

- Start a new Laravel project
- Add Laravel reverb
For the port we use 6001 which was also used for Laravel Websockets
Nginx:
```
location ws {
        proxy_pass                          http://127.0.0.1:6001;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;

        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  https;
        proxy_set_header X-VerifiedViaNginx yes;
        proxy_read_timeout                  60;
        proxy_connect_timeout               60;
        proxy_redirect                      off;

        # Specific for websockets: force the use of HTTP/1.1 and set the Upgrade header
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
}

location /app/ {
        try_files /nonexistent @ws;
}

location /apps/ {
        try_files /nonexistent @ws;
}
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
