### ISSUE TITLE
Everybody can send anything to any private channel without auth

### ISSUE THREAD

**Issue by filzone** [laravel/reverb#272]
### Reverb Version

1.4.2

### Laravel Version

11.x

### PHP Version

8.2.x

### Description

While listening messages on front from private channel - firstly connection is been checked by rules from channels.php 

**But** everyone can send message to any channel without any check using whisper or Echo.connector.pusher.send_event methods

We can see that broadcasting reverb server will pass them without any auth check

And such problem can cause injections with bad things inside message... without any auth from WS server side

Summery:
listening will be checked by rules from channels.php route file
publishing - won't

**PS**: this is actual for reverb version from 1.0.0 to 1.4.2

### Steps To Reproduce

1. create rule for private channel in ./routes/channels.php file
2. forbid it for any user
3. run php artisan reverb:start --debug
4. create simple nodejs app with laravel Echo
5. run nodejs server
6. try to listenToAll your private channel. expected and actual result: 403
7. try to whisper to your private channel. expected: 403, actual - everything will be sent

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by filzone** [comment]
I completely disagree with you.

you can spam "typing" or whisper any other messages to any private chat without auth

Image:

first thing: 2 people are chatting and see "3rd person is typing" - it's bad and weird scenario

second thing: via such behaviour you can "down" frontend app, i.e.: if "typing" event data is an object with some interface in typescript and such spam can cause a lot of problems for users

**Comment by joshuadwire** [comment]
@joedixon Does this project intentionally want to allow whisper from non-authenticated clients? Pusher only allows subscribed clients to send client events for a channel, so allowing unauthenticated whispers is an unexpected difference when Reverb otherwise mirrors Pusher's functionality. 

When switching from Soketi to Reverb, I ran into this issue because my implementation expected the server to add the user_id to the event payload for client-sourced events, which both Soketi and Pusher add automatically. I can submit a PR to add authentication and the user_id if that would be helpful.

**Comment by joedixon** [comment]
Yeah, I think that would work 👍
