### ISSUE TITLE
[Bug] Inconsistent timezone handling between Queues and Reverb Messages in Pulse dashboard

### ISSUE THREAD

**Issue by Minidoracat** [laravel/reverb#278]
### Reverb Version

v1.4.3

### Laravel Version

11.9

### PHP Version

8.3.12

## Description
There is an inconsistency in timezone handling between different components in the Pulse dashboard. While the Queues component correctly displays times in the application's configured timezone (e.g., UTC+8), the Reverb Messages component shows times in UTC regardless of the application's timezone setting.

## Current Behavior
- Queues component: Correctly shows time in the application's configured timezone (e.g., "24/11/29 10:18:00 [GMT+8]")
- Reverb Messages component: Shows time in UTC (e.g., "2024-11-29 02:16:00")

## Expected Behavior
Both components should respect the application's configured timezone setting (`config('app.timezone')`).

### Steps To Reproduce

1. Set application timezone to a non-UTC timezone (e.g., 'Asia/Taipei')
```php
// config/app.php
'timezone' => env('APP_TIMEZONE', 'Asia/Taipei'),
2. Open Pulse dashboard
2. Compare timestamps between Queues and Reverb Messages components

**Comment by joedixon** [comment]
To confirm, are you referring to the timezones updated in Pulse as part of this PR: https://github.com/laravel/pulse/pull/417

**Comment by schonhoff** [comment]
Hello,

I have the same problem on my reverb server. All graphs are MEZ but all reverb cards are UTC. Here are two screenshots from the same pulse server:

![image](https://github.com/user-attachments/assets/9eeb67f3-4ecb-4a09-b527-b951dd3542b7)

![image](https://github.com/user-attachments/assets/de050e6a-b2fe-4c2d-a4fe-050282c3a3b3)

**Comment by Minidoracat** [comment]
> To confirm, are you referring to the timezones updated in Pulse as part of this PR: [laravel/pulse#417](https://github.com/laravel/pulse/pull/417)


Yes, The time format should be consistent across all tooltips. For example:


![image](https://github.com/user-attachments/assets/00f60598-5d49-412e-9c32-fe4fa39786f1)

![image](https://github.com/user-attachments/assets/27ae012d-e990-46b4-bfd4-9352685dad45)

**Comment by joedixon** [comment]
This is a little tricky to implement since we would need to ensure users are running the latest version of Pulse (or at least the version this feature was added). However, you may publish the view and update the timestamps as per the [Pulse implementation](https://github.com/laravel/pulse/pull/417).
