### ISSUE TITLE
forceTLS: false being ignored

### ISSUE THREAD

**Issue by mrjokermr** [laravel/reverb#282]
### Echo Version

1.17.0

### Laravel Version

11.32.0

### PHP Version

8.2

### NPM Version

10.8.2

### Reverb Version

1.4.3

### Laravel Version

11.32.0

### PHP Version

8.2

### Description

I have setup laravel Reverb with laravel-echo on my webserver succesfully and was working fine. After some days of testing I added SSL certificate, now the ws:// connection is swapped to wss:// after changing some .env reverb variables and nginx config.

I don't get the wss:// connection to work. So I want to let Reverb connect through ws:// instead because I tested this connection via Postman and this is stil functioning.

I changed the .env variables like so:
```
REVERB_APP_ID=app_id
REVERB_APP_KEY=hidden_key
REVERB_APP_SECRET=hidden_secret
REVERB_HOST="my.website.url"
REVERB_PORT=6001
REVERB_SERVER_HOST=0.0.0.0
REVERB_SCHEME=http

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

and in bootstrap.js:
```
import axios from 'axios';
window.axios = axios;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

/**
 * Echo exposes an expressive API for subscribing to channels and listening
 * for events that are broadcast by Laravel. Echo and event broadcasting
 * allow your team to quickly build robust real-time web applications.
 */


import Pusher from 'pusher-js';
window.Pusher = Pusher;

import Echo from 'laravel-echo';

window.Echo = new Echo({
    broadcaster: 'reverb',
    key: import.meta.env.VITE_REVERB_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: import.meta.env.VITE_REVERB_PORT,
    wssPort: import.meta.env.VITE_REVERB_PORT,
    forceTLS: false,
    enabledTransports: ['ws'],
});
```
And i have run: php artisan optimize:clear && npm run build.

But still when I check the network tab 
`wss://my.website.url:6001/app/` is being use with wss:// so I think this means forceTLS: false, is being ignored?

More info nginx available-site config:
```
    # Add this block for WebSocket proxying
    location /app/ {
        proxy_pass my.website.url:6001; # Replace with your WebSocket server's IP and port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

### Steps To Reproduce

Not required

### Steps To Reproduce

Not required

**Comment by joedixon** [comment]
If your site is being served over TLS (https), the Pusher client (which powers echo) will only allow you to connect via wss.

**Comment by vedovelli** [comment]
> If your site is being served over TLS (https), the Pusher client (which powers echo) will only allow you to connect via wss.

Thank you very much. This unblocked me!
