### ISSUE TITLE
Laravel Pulse Dashboard not showing Reverb "Connections"

### ISSUE THREAD

**Issue by aalukacsko** [laravel/reverb#283]
### Reverb Version

1.4.3

### Laravel Version

11.33.2

### PHP Version

8.2.7

### Description

I'm integrating Reverb as an update to laravel-echo-server. So far so good. I've implemented the Dashboard as described in the [Monitoring](https://laravel.com/docs/11.x/reverb#monitoring) section. In fact, I didn't have Pulse at all until I integrated for Reverb monitoring. 

I see a graph and data in the "Reverb Messages" card in Pulse, but the "Reverb Connections" card is not showing anything ("No Results"). Running `php artisan reverb:start --debug` there are definitely messages happening and my app is using both presence and private broadcasting channels fine.

Is there something specific with the connection I need to do to see this data? Did I miss something in the docs?

### Steps To Reproduce

I followed the exact steps in the docs [here](https://laravel.com/docs/11.x/reverb#monitoring).

My `config/pulse.php` has the 2 recorders added (along with the `use` statements):

```php
        ReverbConnections::class => [
            'sample_rate' => 1,
        ],

        ReverbMessages::class => [
            'sample_rate' => 1,
        ],
```

And the Pulse `dashboard.blade.php` I've added:

```php
    <livewire:reverb.connections cols="full" />
    
    <livewire:reverb.messages cols="full" />    
```

I see the cards on the dashboard. 

I can share an example from my `channels.php` or the client `Echo` setup but as I mentioned, those are working fine / as expected.

**Comment by joedixon** [comment]
Hey @aalukacsko, did you run the `pulse:check` command?

https://laravel.com/docs/11.x/pulse#capturing-entries

**Comment by aalukacsko** [comment]
Yep - that was it. Since this is *required* to get the card from the Reverb documentation to work at all, I think it would be helpful to have this in the Reverb docs 'Monitoring' section. The only reason I integrated Pulse to any capacity thus far, is Reverb. 

Thanks for the assist though for sure on this!!

**Comment by mugovemachaka** [comment]
Hi guys! I'm trying to record Reverb metrics in Pulse, however I can't seem to find the Reverb recorders in Pulse itself:
`ReverbConnections::class` & `ReverbMessages::class`

Do we need to manually create custom recorders or I'm missing something.

Thanks!
