### ISSUE TITLE
Send Answer without MessageReceived

### ISSUE THREAD

**Issue by KupueIIIKo** [laravel/reverb#285]
### Reverb Version

1.4

### Laravel Version

11

### PHP Version

8.3

### Description

`<?php

class NewMessageListener
{
    //public $queue = 'core';
    /**
     * Handle the event.
     */
    public function handle(MessageReceived $eventData): void
    {
        // Получаем сообщение из payload
        $payload = json_decode($eventData->message);
        
        //Событие
        $event = $payload->event ?? null;
        //echo "event $event\n";

        //Данные
        $data = $payload->data ?? null;
        //var_dump($data);echo "\n";

        $channel = $payload->channel ?? null;

        //Подключение
        $connection_id = $eventData->connection->id();
        //dd($connection_id);

        $session_id = null;
        if(!is_null($channel))
        {
            // Разделяем строку по точке
             $parts = explode('.', $channel);

            // Проверяем, что есть хотя бы две части, и получаем channel_id (вторая часть)
            if(count($parts) > 1){
                $session_id = strrev($parts[1]);
                //echo "session_id - $session_id\n";
            }
        }

        if(is_null($session_id) || is_null($event))
        {
            return;
        }

        if($event == 'SendMessage')
        {
            $eventData->connection->send(json_encode([
                'channel' => $channel,
                'event' => 'MessageReceived',
                'data' => [
                    'message_id'=>$message->id,
                    'update_id'=>$update->id,
                    'temp_id'=>$data->temp_id
                ]
            ]));
        }
        elseif($event == 'getMessages')
        {
                // Если не было найдено сообщений, можно отправить соответствующий ответ
                $eventData->connection->send(json_encode([
                    'channel' => $channel,
                    'event' => 'Messages', 
                    'data' => []  // Отправляем пустой массив
                ]));
            }
        }
        return;
    }
}`

Sending messages works here. But sometimes you need to send messages after processing!

If I work through a queue, then I get that the message is sent to the queue.
Are there any options for creating a connection and sending a response without a queue?
For example, I call
`
					Bus::chain([
						//Отправляем на сервер распознавания языка
						new	AiRequest(['message_id'=>$message->id])
					])->onQueue('default')->dispatch();
`

Internally I use class separation
->sendMessage($this->message->chat_id,$answer,$info);

But when processing JOB, the connection is no longer available. And I need to send a response.

I have already tried many different methods. It is sent through the queue, but after processing..

					
	`
		public function sendMessage($chat_id,$text,$params=null)
	{
		echo "888";
		//Log::info($chat_id);
		$this->checkDefaultinitialized();
		$message_id = $this->generateRandomString();
		$data = [
			'chat_id' => $chat_id,
			'text' => $text,
			'message_id' => $message_id
		];
		// Отправить сообщение через Broadcasting
		//broadcast(new MessageReceived($message->content, $message->user_id));
		//broadcast(new PrivateNewEvent($chat_id, $data));
		// Отправляем событие через Laravel broadcasting
		// Отправляем событие через Laravel broadcasting
        //Broadcast::channel('private-chat.' . $chat_id, function () use ($chat_id,$data) {
        //    event(new PrivateNewEvent($chat_id, $data));
        //});
		// Возвращаем подготовленные данные

		//Log::info('Отправка события PrivateNewEvent', ['channel_id' => $channel_id, 'data' => $data]);
		// Отправляем событие в приватный канал для указанного пользователя
		//Log::info("отправляю ответ");
		//broadcast(new SendMessages($chat_id, $arrayForSend));
		//event(new PrivateNewEvent("$chat_id",$arrayForSend));
		//$result = Request::sendMessage($arrayForSend);
		//return $arrayForSend;
		`
		
		Sends through queues! By the way, there are errors with unicode
		
![image](https://github.com/user-attachments/assets/b9b49741-3bea-4b36-a953-86b64fbe8b72)

How to connect to a socket independently and send a response?

### Steps To Reproduce

Неть

**Comment by joedixon** [comment]
Hey @KupueIIIKo, it's not possible to create a connection inside a queued job (or access and existing connection) because in a job, you are outside the context of Reverb's event loop.

**Comment by KupueIIIKo** [comment]
> Hey @KupueIIIKo, it's not possible to create a connection inside a queued job (or access and existing connection) because in a job, you are outside the context of Reverb's event loop.

Thanks I found a solution for instant sending using ShouldBroadcastNow.

`
<?php

namespace App\Events;

use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PrivateChannel;
//Используется для мгновенной передачи
use Illuminate\Contracts\Broadcasting\ShouldBroadcastNow;
//Добавляет в очередь
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class PrivateNewEvent implements ShouldBroadcastNow
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $data;
    public $channel_id;
    public $eventName;

    /**
     * Создаем новый экземпляр события.
     */
    public function __construct($channel_id, $data,$eventName = 'new_event')
    {
        $this->data = $data; // Данные события
        $this->channel_id = $channel_id; // Идентификатор пользователя для приватного канала
        $this->eventName = $eventName;
    }

    /**
     * Получаем каналы, на которых событие должно быть транслировано.
     *
     * @return array<int, \Illuminate\Broadcasting\Channel>
     */
    public function broadcastOn(): array
    {
        // Используем приватный канал с userId (или session_id) в названии канала
        return [new PrivateChannel('chat.'. $this->channel_id)];
    }

    public function broadcastWith()
    {
        return $this->data;
    }

    public function broadcastAs(): string
    {
        return $this->eventName;
    }
}
`

But the problem with unicode and slashes remains. I think it's a problem in server processing and sending
