### ISSUE TITLE
Add support for protocols other than pusher

### ISSUE THREAD

**Issue by leo108** [laravel/reverb#58]
I know this is not a reasonable request, but...

Pusher is no longer open-source friendly, its React Native SDK stopped supporting custom host since 2022, and they have no plan to add support for it.

FYI: https://github.com/pusher/pusher-websocket-react-native/issues/26

**Comment by joedixon** [comment]
Thanks for the feedback. Reverb has been built to allow support for other protocols, but it's not something we'll be implementing right now.
