### ISSUE TITLE
Presence of `"aws/aws-sdk-php"` in the dependencies?

### ISSUE THREAD

**Issue by olivierphi** [laravel/reverb#59]
### Reverb Version

1.0.0

### Laravel Version

11.0

### PHP Version

any

### Description

Hi there!

Is the `"aws/aws-sdk-php"` package really required to run Reverb? :slightly_smiling_face:   
As it's quite a heavy one (around 40MB), I guess getting rid of it could be good, if it's not actually required by Reverb?

### Steps To Reproduce

- Install Reverb
- Check the dependencies - especially the size of the `vendor/aws/aws-sdk-php` folder

**Comment by Einenlum** [comment]
I confirm it's more than a third of the size of my vendor folder.

![conf](https://github.com/laravel/reverb/assets/5675200/72ce5820-0737-4f26-8b03-deaafd781827)

And I don't see it used anywhere in the reverb package:

![use](https://github.com/laravel/reverb/assets/5675200/c15ce885-d8ac-4e03-a57f-15caa064090f)

**Comment by joedixon** [comment]
Thank you, it's leftover from a previous experiment. Going to remove this now.
