### ISSUE TITLE
Supporting channel events / webhooks

### ISSUE THREAD

**Issue by IllesAprod** [laravel/reverb#64]
Hi,

First of all, thanks for the awesome package! 

We are currently using soketi and wanted to migrate over, but as far as I see Reverb currently not supporting webhooks and we are heavily relying on the channel occupied / vacated webhook events.

I just wanted to ask if is there any plan to implement webhooks or even better to have the ability to fire a Job when a specific event happened?

Thanks for the reply!

**Comment by joedixon** [comment]
We don't have plans right now as we want to make sure Reverb is as fast as possible. Adding webhooks likely has the side effect of blocking the event loop.

We do already fire a `MessageSent` and `MessageRecevied` event which receives the connection and the message payload, so you could hook into this. The same applies re: blocking the event loop so you'd probably want to shunt any heaving lifting off to the queue or something.

Would that solve your problem or are you looking for events like channels being vacated etc. Would love to hear more about your use case.

**Comment by IllesAprod** [comment]
Thanks for the reply! 

We are using these events to track users activity. 
Our current stack is soketi.app and a Laravel backend.

This is the workflow we are having now:
1. User loads our site
2. Echo joins to a specific channel like `users.{id}`
3. Soketi calls a webhook with "channel occupied" event to our Laravel backend
4. The backend based on the parameters sets the user "active"
5. When the user left the site, soketi calls a webhook with "channel vacated"
6. The backend sets the user "inactive"

I think having `ChannelOccupied` and `ChannelVacated` events we could make a workaround replacing webhooks with queue jobs.

Also I wanted to mention that soketi and pusher have the same webhooks specification, so in the future that would make sense for me to support webhooks for easier migration to Reverb.

**Comment by joedixon** [comment]
Thanks for the context. I'm going to close this for now, but will give some thought as to if/how I can make this happen.

**Comment by Neodark7** [comment]
Hi ! Same issue here, i'd really like to migrate my company project from soketi to reverb, unfortunately i also need those "ChannelOccupied" / "ChannelVacated" events :/
