### ISSUE TITLE
Run standalone, outside of application

### ISSUE THREAD

**Issue by atymic** [laravel/reverb#68]
We run our application on Laravel Vapor, and currently run socketi on ECS for pusher websockets.
Is there the option to run reverb standalone, without dependance on the app's code (ie, installing it into the laravel application)?

Thanks!

**Comment by Jubeki** [comment]
You can create a new Laravel Application and install only Reverb. Then you can configure multiple applications (or only on other application).

You can then run the new Laravel Reverb Application on ECS.

**Comment by driesvints** [comment]
No it's not possible.
