### ISSUE TITLE
Don't assume resources/js is present

### ISSUE THREAD

**Issue by tarreislam** [laravel/reverb#77]
### Reverb Version

1.0.0

### Laravel Version

11.0

### PHP Version

8.3

### Description

I am using Laravel purely as a backend HTTP API but your installer assumes `/resources/js` should exist, which it does not in my case.

Teherefore I get this error when running `art install:broadcasting`

`copy(/var/www/resources/js/echo.js): Failed to open stream: No such file or directory` at vendor/laravel/framework/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php:58

### Steps To Reproduce

1. php artisan install:broadcasting

**Comment by joedixon** [comment]
Did you say "No" when the installer asked you if you wish to install the NPM dependencies?

**Comment by tarreislam** [comment]
> Did you say "No" when the installer asked you if you wish to install the NPM dependencies?

That question is asked after this exception is thrown.

**Exception thrown**

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php#L57

**Question about NPM dependencies**
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php#L76


This might be an framework issue and not reverb issue though?

**Comment by joedixon** [comment]
It's actually both, going to be working on this today.

**Comment by driesvints** [comment]
@tarreislam did you try this on Laravel v11.0.5? We fixed this here normally: https://github.com/laravel/framework/pull/50519

**Comment by tarreislam** [comment]
> @tarreislam did you try this on Laravel v11.0.5? We fixed this here normally: [laravel/framework#50519](https://github.com/laravel/framework/pull/50519)

When I upgrade I landed on 11.03, so its probably that!
