### ISSUE TITLE
Does not work in Safari

### ISSUE THREAD

**Issue by fylzero** [laravel/reverb#82]
### Reverb Version

1.0.0-beta2

### Laravel Version

11.0.5

### PHP Version

8.3.3

### Description

Laravel Reverb works fine in Chrome and Firefox but does not seem to work at all in Safari for me

### Steps To Reproduce

Install Reverb, test in Chrome, FF, and Safari. Safari does nothing.

**Comment by joedixon** [comment]
Hey @fylzero Can you ensure you have `REVERB_HOSTNAME=localhost` in your environment file rather than `0.0.0.0`

**Comment by fylzero** [comment]
@joedixon I have it set to the Herd/Valet domain. `myapp.test` as I am using this with a Herd SSL and the instructions on the Herd page say to do this. I have tried localhost and 0.0.0.0 and they do not work with SSL at all.

**Comment by fylzero** [comment]
I just woke up and responded too quickly. I actually did not get SSL working with Herd/Reverb. I will try changing this again today and see if it resolves thr Safari issue.

**Comment by fylzero** [comment]
Turns out Safari kept forcing my http connection to https and I didn't notice since scheme is hidden in the URL bar. Confirmed Safari is working. Thanks!
