### ISSUE TITLE
Invalid response data of event pusher_internal:subscription_succeeded

### ISSUE THREAD

**Issue by pnlinh-it** [laravel/reverb#92]
### Reverb Version

v1.0.0-beta3

### Laravel Version

v11.0.7

### PHP Version

8.2.17

### Description

According [Pusher protocol documentation](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#pusher_internalsubscription_succeeded-pusher-channels-greater-client), after subscribe to presence channel success, the `ids` field in data response of the event `pusher_internal:subscription_succeeded` should be `Array`. 

Currently, Reverb response a map with key is socketId:

![image](https://github.com/laravel/reverb/assets/11713395/0eb0a114-28ac-4a19-9d39-65354c09a39c)

<img width="355" alt="image" src="https://github.com/laravel/reverb/assets/11713395/6d3364c6-bdc5-4b42-940e-1b3a4f4ce3f3">

After take a look at Reverb, I see that the response data is handled at: [InteractsWithPresenceChannels.php#L76](https://github.com/laravel/reverb/blob/main/src/Protocols/Pusher/Channels/Concerns/InteractsWithPresenceChannels.php#L76). 

Currently it uses `all()` method to get array from collection but it will keep the array key. So I think we should use `->values()->all()` to reset the array key.

I wonder if i can create PR?

### Steps To Reproduce

I created demo project at here: https://github.com/pnlinh-it/demo-revert-issue

**Comment by joedixon** [comment]
Thanks @pnlinh-it, would be happy to receive a PR for this.

**Comment by joedixon** [comment]
Resolved by #95, thank you @pnlinh-it 🙌

**Comment by pnlinh-it** [comment]
@joedixon Thank you for quick action 🎊
