### ISSUE TITLE
Payload too large

### ISSUE THREAD

**Issue by ondraasek** [laravel/reverb#96]
### Reverb Version

1.0

### Laravel Version

11.0.3

### PHP Version

8.3

### Description

Hello, I am using laravel reverb and sending bigger data and getting exception Payload is too large. do you have an idea how to overcome this? looking for 50-100 kb message size limit, checked that on Discord and some ppl told me its bug probably, so reporting here. thank you so much.

### Steps To Reproduce

do bigger messages 50kb+

**Comment by joedixon** [comment]
Hey @ondraasek, we have a fix merged for this and we'll likely tag a new release tomorrow: https://github.com/laravel/reverb/pull/87
