### ISSUE TITLE
Reverb Messages Events don't get listened to when using Herd Pro

### ISSUE THREAD

**Issue by aj-norman** [laravel/reverb#97]
### Reverb Version

1.0.0-beta3

### Laravel Version

11.0.6

### PHP Version

8.3.3

### Description

When using Laravel Reverb via Herd Pro, the `MessageReceived` & `MessageSent` don't get listened to by the sites within Herd Pro. This then has a knock on effect when using Laravel Pulse locally to see how many messages are sent.

Running Laravel Reverb within the project folder/site fixes the issue.

Apologies in advance if this is the wrong location for the issue

### Steps To Reproduce

- Create a new Laravel project with broadcasting enabled w/ Reverb
- Install Laravel Pulse & run work and check
- Start Laravel Reverb via Herd
- Send a broadcast message

**Comment by joedixon** [comment]
Herd's Reverb service is standalone and not linked to your application so your application won't be able to listen for the events. It's meant to be used if you want to keep your WebSocket server separate from your application.
